export const QUERY_KEYS = {
  CASE_INFO: 'caseInfo',
  CASE_MATERIAL: 'caseMaterial',
  AUTO_RECLASSIFY: 'autoReclassify',
  RENAME_MATERIAL: 'renameMaterial',
  READ_STATUS: 'readStatus',
  PCD_REQUESTS: 'pcdRequests',
  PCD_REQUEST: 'pcdRequest',
  BULK_SET_UNUSED: 'bulkSetUnused',
  CASE_MATERIAL_DOCUMENT_PREVIEW: 'caseMaterialDocumentPreview',
  CASE_MATERIAL_DISCARD: 'caseMaterialDocumentPreview',
  CASE_MATERIAL_FULL_DOCUMENT: 'caseMaterialFullDocument',
  DOCUMENT_TYPES: 'documentTypes',
  CASE_WITNESSES: 'caseWitnesses',
  RECLASSIFY: 'reclassify',
  WITNESS_STATEMENTS: 'witnessStatements',
  EXHIBIT_PRODUCERS: 'exhibitProducers',
  PCD_REVIEW_CORE: 'pcdReviewCore',
  PCD_REVIEW_REVIEW_DETAILS: 'pcdReviewReviewDetails',
  RECLASSIFY_MATERIAL: 'reclassifyMaterial',
  CASE_SEARCH: 'caseSearch',
  DOCUMENT_SEARCH: 'documentSearch',
  GET_ALL_DOCUMENTS: 'getAllDocuments',
  UPDATE_STATEMENT: 'updateStatement',
  UPDATE_EXHIBIT: 'updateExhibit',
};

export const DEFAULT_RESULTS_PER_PAGE = 20;
