---
name: '$(majorMinorVersion).$(Year:yy)$(DayOfYear).$(semanticVersion)-ci'

trigger:
  batch: true
  branches:
    include:
      - development 
  paths:
    include:
      - materials_ui
      - terraform

pr: none

variables:
  - name: buildConfiguration
    value: "Release"
  - name: majorMinorVersion
    value: "1.0"
  - name: semanticVersion
    value: "$[counter(variables['majorMinorVersion'], 1)]"
  - name: nodeVersion
    value: "24.x"
  - name: workingDir
    value: "materials_ui"
  - group: materials-global
  - group: materials-ui-spa

pool:
  name: $(dev-build-agent)

stages:
  - stage: Publish_Artifacts
    displayName: Publish Pipeline Artifacts
    jobs:

      - job: Build_Terraform_Artifacts
        steps:
          - task: PublishPipelineArtifact@1
            displayName: "Publish terraform artifact"
            inputs:
              targetPath: "$(Pipeline.Workspace)/s/terraform/"
              artifact: '$(targetTerraformArtifact)'
              publishLocation: "pipeline"
 
      # - job: Build_Script_Artifacts
      #   steps:
      #     - task: PublishPipelineArtifact@1
      #       displayName: "Publish pipeline scripts"
      #       inputs:
      #         targetPath: "$(Pipeline.Workspace)/s/materials_devops_pipelines/scripts"
      #         artifact: "materials-script-files"
      #         publishLocation: "pipeline"

      - job: Build_UI_Artifacts
        steps:

          # Setup Node.js
          - task: UseNode@1
            displayName: "Use Node.js"
            inputs:
              version: "$(nodeVersion)"
            
          - task: Npm@1
            inputs:
              command: "ci"
              workingDir: '$(workingDir)'
            displayName: 'Install Dependencies'

          - task: Npm@1
            displayName: "Build UI Package"
            inputs:
              command: "custom"
              workingDir: '$(workingDir)'
              customCommand: "run build"

          - task: PublishPipelineArtifact@1
            displayName: "Publish UI artifact"
            inputs: 
              targetPath: '$(workingDir)/materials_ui/dist'
              artifact: '$(targetUIArtifact)'
              publishLocation: "pipeline"

