---
name: '$(majorMinorVersion).$(Year:yy)$(DayOfYear).$(semanticVersion)-ci'

trigger:
  batch: true
  branches:
    include:
      - development 
  paths:
    include:
      - materials_ui
      - terraform

pr: none

variables:
  - name: buildConfiguration
    value: "Release"
  - name: majorMinorVersion
    value: "1.0"
  - name: semanticVersion
    value: "$[counter(variables['majorMinorVersion'], 1)]"
  - name: nodeVersion
    value: "24.x"
  - name: workingDir
    value: "materials_ui"
  - group: materials-global
  - group: materials-ui-spa-dev

pool:
  name: $(dev-build-agent)

stages:
  - stage: Publish_Artifacts
    displayName: Publish Pipeline Artifacts
    jobs:

      - job: Build_Terraform_Artifacts
        steps:
          - task: PublishPipelineArtifact@1
            displayName: "Publish terraform artifact"
            inputs:
              targetPath: "$(Pipeline.Workspace)/s/terraform/"
              artifact: '$(targetTerraformArtifact)'
              publishLocation: "pipeline"
 
      # - job: Build_Script_Artifacts
      #   steps:
      #     - task: PublishPipelineArtifact@1
      #       displayName: "Publish pipeline scripts"
      #       inputs:
      #         targetPath: "$(Pipeline.Workspace)/s/materials_devops_pipelines/scripts"
      #         artifact: "materials-script-files"
      #         publishLocation: "pipeline"

      - job: Build_UI_Artifacts
        steps:

          # Add build version
          - task: PowerShell@2
            displayName: "Record build version"
            inputs:
              targetType: "inline"
              workingDirectory: '$(workingDir)/public'
              script: |
                New-Item build-version.txt -force
                $currentDate = Get-Date
                Set-Content build-version.txt "{`"name`":`"ui`",`"buildVersion`":`"$(Build.BuildNumber)`",`"sourceVersion`":`"$(Build.SourceVersion)`",`"lastBuilt`":`"$currentDate`"}"

          # Setup Node.js
          - task: UseNode@1
            displayName: "Use Node.js"
            inputs:
              version: "$(nodeVersion)"
            
          - task: Npm@1
            inputs:
              command: "ci"
              workingDir: '$(workingDir)'
            displayName: 'Install Dependencies'

          - task: Npm@1
            displayName: "Build UI Package"
            inputs:
              command: "custom"
              workingDir: '$(workingDir)'
              customCommand: "run build"
            env:
              VITE_MSAL_CLIENT_ID: $(MSAL_CLIENT_ID)
              VITE_MSAL_TENANT_ID: $(MSAL_TENANT_ID) 
              VITE_MSAL_REDIRECT_URI: $(MSAL_REDIRECT_URI) 
              VITE_POLARIS_GATEWAY_URL: $(POLARIS_GATEWAY_URL)
              VITE_POLARIS_GATEWAY_SCOPE: $(POLARIS_GATEWAY_SCOPE)
              VITE_GLOBAL_SCRIPT_URL: $(GLOBAL_SCRIPT_URL)

          - task: replacetokens@5
            displayName: "Replace CSP value in serve.json with appropriate values for dev/staging/prod"
            inputs:
              rootDirectory: '$(Pipeline.Workspace)/s/materials_ui/'
              targetFiles: |
                serve.json
              encoding: 'utf-8'
              tokenPattern: 'default'

          - task: CopyFiles@2
            displayName: "Copy serve.json into build"
            inputs:
              SourceFolder: '$(Pipeline.Workspace)/s/materials_ui/'
              Contents: |
                serve.json           
              TargetFolder: '$(workingDir)/build'

          - task: PublishPipelineArtifact@1
            displayName: "Publish Web UI artifact"
            inputs:
              targetPath: '$(workingDir)/build'
              artifact: '$(targetUIArtifact)'
              publishLocation: "pipeline"