---
name: '$(majorMinorVersion).$(Year:yy)$(DayOfYear).$(semanticVersion)'
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: MaterialsBuild
      source: materials-infra-tf-qa-build
      trigger:
        branches:
          include:
            - refs/heads/main
        stages:
          - Publish_Artifacts

parameters:
- name: TF_Apply
  displayName: Apply TF change
  type: boolean
  default: false

pool:
  name: $(qa-build-agent)

variables:
  - name: majorMinorVersion
    value: 1.0
  - name: semanticVersion 
    value: $[counter(variables['majorMinorVersion'], 1)]
  - group: materials-kv-qa-terraform
  - group: materials-global

stages:
                 
  - stage: Apply_QA
    displayName: Deployment > Materials QA
    jobs:      
      - deployment: CI_Deploy_Materials_Terraform
        workspace:
          clean: all 
        environment: "Materials_QA"   
        strategy:
          runOnce:
            deploy:
              steps:
              
                - template: templates/task_get-credentials.yml
                  parameters:
                    azureSubscription: $(qa-azure-service-connection)

                - template: templates/task_apply-terraform.yml
                  parameters:
                    targetBuild: $(targetBuild)
                    targetTerraformArtifact: $(targetTerraformArtifact)
                    targetPlanName: "qa"
                    terraformStorageAccount: $(qa-terraform-storage-account)
                    terraformContainerName: $(materials-terraform-container-name)
                    terraformStateKey: $(terraform-key)
                    terraformStateResourceGroup: $(terraform-resource-group)
                    armClientId: $(clientId)
                    armClientSecret: $(clientSecret)
                    armTenantId: $(tenantId)
                    armSubscriptionId: $(subscriptionId)
                    TF_Apply: ${{ parameters.TF_Apply }}
                    terraformVersion: $(terraform-version)